//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

[DataContract]//need to specify the iteams that you want to show

public partial class students
{
    [DataMember]//will be showed
    public int Idstd { get; set; }
    [DataMember]
    public string Nom { get; set; }
    [DataMember]
    public string Prenom { get; set; }
    [DataMember]
    public int Age { get; set; }
}
